feat: реализовать функциональность основного сервиса
VIashunin/java-explore-with-me pull request #4
Opened 2023-07-20 22:00 UTC by VIashunin

2023-07-23 06:32 UTC, Fleaman777 requested changes

2023-07-23 06:32 UTC, Fleaman777 commented on ewm-main/src/main/java/ru/practicum/main/categories/admin/service/AdminCategoryServiceImpl.java
> +        Category outdatedCategory = categoryRepository.findById(catId).orElseThrow(/*() -> new NotFoundException("Category with id:" + catId + " is not found.")*/);
а чего закомментировал код, 
хорошо бы обработать ситуацию с эксепшеном

2023-07-23 06:32 UTC, Fleaman777 commented on ewm-main/src/main/java/ru/practicum/main/compilations/admin/service/AdminCompilationServiceImpl.java
> +            }
эту часть можно было бы сделать через стрим

2023-07-23 06:32 UTC, Fleaman777 commented on ewm-main/src/main/java/ru/practicum/main/compilations/admin/service/AdminCompilationServiceImpl.java
> +@Transactional
лучше не вешать транзакцию на весь ккласс, 
это может тормозить работу всего приложения, если вдруг один из запросов будет долго выполнятся. 

правильней было бы использовать ее на конкретных методах

2023-07-23 06:32 UTC, Fleaman777 commented on ewm-main/src/main/java/ru/practicum/main/events/admin/service/AdminEventServiceImpl.java
> +}
длинный метод тяжелее воспринимать, поэтому хорошо было бы его разделить.
какую-то логику вынести в отдельные вспомогательные методы

2023-07-23 06:32 UTC, Fleaman777 commented on ewm-main/src/main/java/ru/practicum/main/events/common/service/CommonEventServiceImpl.java
> +    }
и здесь аналагично предыдущему комментарию

аналагично в других похожих местах

2023-07-23 06:32 UTC, Fleaman777 commented on ewm-main/src/main/java/ru/practicum/main/events/individual/service/IndividualEventServiceImpl.java
> +        if (event.getState().equals(EventStatus.PENDING) || event.getState().equals(EventStatus.CANCELED)) {
енамы хорошо сравнивать через == 
так и сравнивается быстрее, и выглядит чуть очевидней

аналагично в др местах

2023-07-23 06:32 UTC, Fleaman777 commented on ewm-main/src/main/java/ru/practicum/main/events/mapper/EventMapper.java
> +    }
выглядит как метод, который можно написать через стрим

2023-07-23 10:02 UTC, VIashunin commented on ewm-main/src/main/java/ru/practicum/main/categories/admin/service/AdminCategoryServiceImpl.java
> +        Category outdatedCategory = categoryRepository.findById(catId).orElseThrow(/*() -> new NotFoundException("Category with id:" + catId + " is not found.")*/);
случайно закомментировал, забыл убрать
сейчас исправил

2023-07-23 10:05 UTC, VIashunin commented on ewm-main/src/main/java/ru/practicum/main/compilations/admin/service/AdminCompilationServiceImpl.java
> +            }
выполнил эту часть через стрим

2023-07-23 10:17 UTC, VIashunin commented on ewm-main/src/main/java/ru/practicum/main/compilations/admin/service/AdminCompilationServiceImpl.java
> +@Transactional
Понял, учту этот момент в будущем
Просто в данном случае у нас всего 3 метода в классе и все они изменяют состояние данных в бд
Именно поэтому я для всех методов решил применить транзакции и вынес аннотацию над классом

2023-07-23 10:22 UTC, VIashunin commented on ewm-main/src/main/java/ru/practicum/main/events/mapper/EventMapper.java
> +    }
исправил метод через стрим

2023-07-23 10:34 UTC, VIashunin commented on ewm-main/src/main/java/ru/practicum/main/events/admin/service/AdminEventServiceImpl.java
> +}
вынес некоторую логику в отдельный метод

2023-07-23 11:50 UTC, VIashunin commented on ewm-main/src/main/java/ru/practicum/main/events/individual/service/IndividualEventServiceImpl.java
> +        if (event.getState().equals(EventStatus.PENDING) || event.getState().equals(EventStatus.CANCELED)) {
исправил сравнение всех енамов по проекту на ==

2023-07-24 08:15 UTC, Fleaman777 commented on ewm-main/src/main/java/ru/practicum/main/compilations/admin/service/AdminCompilationServiceImpl.java
> +@Transactional
ага, так и подумал. 
в целом, если использовать @Transactional над классом, так и получается, что все методы класса становятся транзакционными, что в твоем случае и надо, 
но если вдруг в этот класс будут добавляться новые методы, которые будут на чтение, то можно упустить момент, и в итоге новые методы тоже будут в транзации, что не очень хорошо

2023-07-24 08:16 UTC, Fleaman777 approved these changes

2023-07-24 17:17 UTC, merged